name: consumidor

on:
  push:
    branches:
      - main

jobs:

  reusable-job:

    uses: ./.github/workflows/reusable.yml

    with:
      node-version: '18'
      artifact-name: 'node18'

  reusable-job-node20:

    uses: ./.github/workflows/reusable.yml

    with:
      node-version: '20'
      artifact-name: 'node20'

  custom-job:

    runs-on: ubuntu-latest

    needs:
      - reusable-job
      - reusable-job-node20

    steps:

      - name: Mostrar outputs
        run: |
          echo "Resultado Node18: ${{ needs.reusable-job.outputs.test-status }}"
          echo "Resultado Node20: ${{ needs.reusable-job-node20.outputs.test-status }}"

      - name: Lógica adicional
        run: echo "Pipeline consumidor ejecutando tareas propias"
